[features]
seeds = false
[programs.localnet]
solana_twitter = "AcDEr8rP5NMXpY9nQFcNqQuYABVWBwsJ4zDcvELVFigo"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "/home/johnliu/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
